//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    
    public partial class buscar_Result1
    {
        public int Lng_IdCliente { get; set; }
        public string Txt_NumCliente { get; set; }
        public string Txt_Cliente { get; set; }
        public string Txt_Direccion { get; set; }
        public string Txt_Identificacion { get; set; }
        public string Txt_Telefono { get; set; }
        public string Txt_Email { get; set; }
        public Nullable<System.DateTime> Fec_Alta { get; set; }
    }
}
