//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxaVenta
    {
        public Nullable<int> IdTaxa { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> Dia { get; set; }
        public int Lng_IdTaxa { get; set; }
        public int Int_IdMoneda { get; set; }
    }
}
