//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ArqueoTesoria
    {
        public int Lng_IdRegistro { get; set; }
        public Nullable<decimal> Dbl_Monto { get; set; }
        public Nullable<decimal> Dbl_MontoSuc { get; set; }
        public Nullable<int> Int_IdMoneda { get; set; }
        public Nullable<bool> Bol_Ok { get; set; }
        public Nullable<int> Int_IdUsuario { get; set; }
        public Nullable<int> Int_IdSucursal { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public Nullable<int> Int_IdEstatusArq { get; set; }
        public Nullable<int> Lng_IdArqueoMoneda { get; set; }
    }
}
