//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cancelaciones
    {
        public int Lng_IdCancelacion { get; set; }
        public string Txt_Motivo { get; set; }
        public Nullable<int> Lng_IdRegistro { get; set; }
        public Nullable<int> Lng_IdUsuario { get; set; }
        public Nullable<System.DateTime> Fec_Cancelacion { get; set; }
    }
}
