//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_DotGrupo
    {
        public int Lng_IdotGrupo { get; set; }
        public Nullable<int> Lng_IdDotacion { get; set; }
        public Nullable<int> Int_IdGrupo { get; set; }
        public Nullable<bool> Bol_Activo { get; set; }
        public string Txt_Motivo { get; set; }
    }
}
