//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Dotaciones
    {
        public int Lng_IdDotacion { get; set; }
        public Nullable<int> Lng_IdSucursal { get; set; }
        public Nullable<decimal> Dbl_Monto { get; set; }
        public Nullable<int> Int_IdMoneda { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public Nullable<int> Int_Idusuario { get; set; }
        public Nullable<int> Int_EstatusDot { get; set; }
    }
}
