//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_EntEmp
    {
        public int Lng_IdEntEmp { get; set; }
        public Nullable<int> Lng_IdEntrada { get; set; }
        public Nullable<int> Int_IdUsuario { get; set; }
        public Nullable<int> Int_IdTurno { get; set; }
        public Nullable<System.DateTime> Fec_Ini { get; set; }
        public Nullable<System.DateTime> Fec_Fin { get; set; }
        public Nullable<int> Lng_IdSalida { get; set; }
    }
}
