//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Personalizacion
    {
        public int Lng_Idregistro { get; set; }
        public string Nom_Empresa { get; set; }
        public byte[] img_Logo { get; set; }
        public byte[] img_Baner { get; set; }
    }
}
