//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PlazasApli
    {
        public int Lng_IdPlazasApli { get; set; }
        public Nullable<int> Lng_IdTaxa { get; set; }
        public Nullable<int> Int_IdPlazas { get; set; }
    }
}
