//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_Registros
    {
        public int Lng_IdRegistro { get; set; }
        public Nullable<int> Int_IdTipoTran { get; set; }
        public Nullable<int> Int_IdMoneda { get; set; }
        public Nullable<int> Int_IdMonVenta { get; set; }
        public Nullable<decimal> Dbl_MontoRecibir { get; set; }
        public Nullable<decimal> Dbl_MontoPagar { get; set; }
        public Nullable<decimal> Dbl_TipoCambio { get; set; }
        public Nullable<decimal> Dbl_TipoCambioven { get; set; }
        public Nullable<decimal> Dbl_TipoCambioEsp { get; set; }
        public Nullable<bool> Bol_Cancelar { get; set; }
        public Nullable<decimal> Dbl_Entregar { get; set; }
        public Nullable<decimal> Dbl_Cambio { get; set; }
        public Nullable<int> Int_IdTpv { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fec_Fecha { get; set; }
        public Nullable<bool> Bol_multimoneda { get; set; }
        public Nullable<int> Lng_IdSucursal { get; set; }
        public Nullable<bool> Bol_Especial { get; set; }
        public byte[] Txt_MsgEspecial { get; set; }
    }
}
