//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_SalidaSuc
    {
        public int Lng_IdSalida { get; set; }
        public Nullable<decimal> Dbl_SaldoSalida { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fec_Fin { get; set; }
        public Nullable<int> Int_IdMoneda { get; set; }
        public Nullable<int> int_IdSucursal { get; set; }
        public Nullable<bool> Bol_Activo { get; set; }
        public Nullable<int> Int_Idusuario { get; set; }
        public Nullable<int> Int_IdTurno { get; set; }
    }
}
