//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SalidaSuc
    {
        public int Lng_IdSalida { get; set; }
        public Nullable<decimal> Dbl_SaldoSalida { get; set; }
        public Nullable<System.DateTime> Fec_Fin { get; set; }
        public Nullable<int> Int_IdMoneda { get; set; }
        public Nullable<int> int_IdSucursal { get; set; }
    }
}
