//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Taxas
    {
        public int Lng_IdTaxa { get; set; }
        public Nullable<int> Int_IdMoneda { get; set; }
        public Nullable<decimal> dbl_Valor { get; set; }
        public Nullable<bool> Bol_Tipo { get; set; }
        public Nullable<System.DateTime> Fec_Dia { get; set; }
        public Nullable<System.DateTime> Fec_Vencimiento { get; set; }
        public Nullable<int> Int_IdGrupo { get; set; }
    }
}
