//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_TicketTesoreria
    {
        public int Lng_IdArchivo { get; set; }
        public Nullable<int> Lng_IdTesoreria { get; set; }
        public byte[] Img_Archivo { get; set; }
        public Nullable<System.DateTime> Fec_Dia { get; set; }
        public Nullable<bool> Bol_Activo { get; set; }
    }
}
